export const ORCHESTRA_SCORE_ORDER = [
    'orchestra', // name of score for user interface selection
    'score',
    // woodwinds
    'piccolo',
    'flute',
    'oboe',
    'english_horn',
    'bassoon',
    'bb_clarinet',
    'bass_clarinet',
    'alto_saxophone',
    'tenor_saxophone',
    'baritone_saxophone',
    // brass
    'f_horn',
    'horn in f',
    'c_trumpet',
    'bb_trumpet',
    'trumpet in bb',
    'trombone',
    'bass_trombone',
    'euphonium',
    'tuba',
    // timpani
    'timpani',
    // non-pitched percussion
    'templeblocks',
    'handclap',
    'drum kit',
    'drumset',
    'bass_drum',
    // pitched percussion
    'chimes',
    'percussion',
    // keyboard percussion
    'glockenspiel',
    'xylophone',
    'marimba',
    'vibraphone',
    // other
    'harp',
    'piano',
    'synthesizer',
    'electric_guitar',
    'electric_bass',
    //strings
    'violin',
    'viola',
    'cello',
    'contrabass',
];

export const BAND_SCORE_ORDER = [
    'concert band', // name of score for user interface selection
    'score',
    'piccolo',
    'flute',
    'oboe',
    'english_horn',
    'bassoon',
    'bb_clarinet',
    'bass_clarinet',
    'alto_saxophone',
    'tenor_saxophone',
    'baritone_saxophone',
    'c_trumpet',
    'bb_trumpet',
    'trumpet_in_bb',
    'f_horn',
    'horn_in_f',
    'trombone',
    'bass_trombone',
    'euphonium',
    'tuba',
    'string_bass',
    'electric_bass',
    'percussion',
    'drumset',
]