export const ORCHESTRA_SCORE_ORDER = [
    'orchestra', // name of score for user interface selection
    'score',
    'piccolo',
    'flute',
    'oboe',
    'english_horn',
    'bassoon',
    'bb_clarinet',
    'bass_clarinet',
    'alto_saxophone',
    'tenor_saxophone',
    'baritone_saxophone',
    'c_trumpet',
    'bb_trumpet',
    'trumpet in bb',
    'f_horn',
    'horn in f',
    'trombone',
    'bass_trombone',
    'euphonium',
    'tuba',
    'string_bass',
    'electric_bass',
    'percussion',
    'drum kit',
    'drumset',
    'harp',
    'piano',
    'violin',
    'viola',
    'cello',
    'contrabass',
];

export const BAND_SCORE_ORDER = [
    'concert band', // name of score for user interface selection
    'score',
    'piccolo',
    'flute',
    'oboe',
    'english_horn',
    'bassoon',
    'bb_clarinet',
    'bass_clarinet',
    'alto_saxophone',
    'tenor_saxophone',
    'baritone_saxophone',
    'c_trumpet',
    'bb_trumpet',
    'trumpet_in_bb',
    'f_horn',
    'horn_in_f',
    'trombone',
    'bass_trombone',
    'euphonium',
    'tuba',
    'string_bass',
    'electric_bass',
    'percussion',
    'drumset',
]